"""
Generates a compliance PDF report from batch processing results.
Uses fpdf2 if available; falls back to plain-text .txt report.
"""

from pathlib import Path
from datetime import datetime


def _txt_report(results: dict, report_path: Path, guideline: str):
    """Plain-text fallback report."""
    lines = [
        f"CLINICAL IMAGE COMPLIANCE REPORT",
        f"Generated: {datetime.utcnow().strftime('%Y-%m-%d %H:%M UTC')}",
        f"Guideline: {guideline}",
        f"=" * 60,
        f"Total processed : {results['processed']}",
        f"Compliant        : {results['compliant']}",
        f"Non-compliant    : {results['non_compliant']}",
        f"Processing time  : {results['elapsed_sec']}s",
        f"",
        f"PER-IMAGE DETAIL",
        f"-" * 60,
    ]
    for item in results["items"]:
        lines.append(f"File      : {item['file']}")
        lines.append(f"Status    : {item['status']}")
        lines.append(f"Guideline : {item['guideline']}")
        m = item.get("metrics", {})
        if m:
            lines.append(f"SNR       : {m.get('snr_before', 'N/A')} -> {m.get('snr_after', 'N/A')}  (+{m.get('snr_gain_pct', 'N/A')}%)")
            lines.append(f"Contrast  : {m.get('contrast_before', 'N/A')} -> {m.get('contrast_after', 'N/A')}  (+{m.get('contrast_gain_pct', 'N/A')}%)")
        lines.append(f"Compliant : {'YES' if item.get('compliance_pass') else 'NO'}")
        lines.append(f"Exports   : {', '.join(item.get('exports', []))}")
        lines.append("-" * 60)

    txt_path = report_path.with_suffix(".txt")
    txt_path.write_text("\n".join(lines))
    print(f"[INFO] Text report (fpdf2 not installed): {txt_path}")


def generate_report(results: dict, report_path: Path, guideline: str):
    """Generate PDF compliance report; fall back to .txt if fpdf2 missing."""
    try:
        from fpdf import FPDF

        pdf = FPDF()
        pdf.set_auto_page_break(auto=True, margin=15)
        pdf.add_page()
        pdf.set_font("Helvetica", "B", 16)
        pdf.cell(0, 10, "Clinical Image Compliance Report", ln=True)
        pdf.set_font("Helvetica", "", 10)
        pdf.cell(0, 6, f"Generated: {datetime.utcnow().strftime('%Y-%m-%d %H:%M UTC')}", ln=True)
        pdf.cell(0, 6, f"Guideline: {guideline}", ln=True)
        pdf.ln(4)

        pdf.set_font("Helvetica", "B", 12)
        pdf.cell(0, 8, "Summary", ln=True)
        pdf.set_font("Helvetica", "", 10)
        pdf.cell(0, 6, f"Total processed : {results['processed']}", ln=True)
        pdf.cell(0, 6, f"Compliant       : {results['compliant']}", ln=True)
        pdf.cell(0, 6, f"Non-compliant   : {results['non_compliant']}", ln=True)
        pdf.cell(0, 6, f"Processing time : {results['elapsed_sec']}s", ln=True)
        pdf.ln(4)

        pdf.set_font("Helvetica", "B", 12)
        pdf.cell(0, 8, "Per-Image Detail", ln=True)

        for item in results["items"]:
            pdf.set_font("Helvetica", "B", 10)
            pdf.cell(0, 6, f"File: {item['file']}", ln=True)
            pdf.set_font("Helvetica", "", 10)
            pdf.cell(0, 5, f"  Status    : {item['status']}", ln=True)
            m = item.get("metrics", {})
            if m:
                pdf.cell(0, 5,
                    f"  SNR       : {m.get('snr_before','N/A')} -> {m.get('snr_after','N/A')} (+{m.get('snr_gain_pct','N/A')}%)",
                    ln=True)
                pdf.cell(0, 5,
                    f"  Contrast  : {m.get('contrast_before','N/A')} -> {m.get('contrast_after','N/A')} (+{m.get('contrast_gain_pct','N/A')}%)",
                    ln=True)
            compliant_str = "PASS" if item.get("compliance_pass") else "FAIL"
            pdf.cell(0, 5, f"  Compliance: {compliant_str} ({guideline})", ln=True)
            for exp in item.get("exports", []):
                pdf.cell(0, 5, f"  Export    : {exp}", ln=True)
            pdf.ln(2)

        pdf.set_font("Helvetica", "I", 8)
        pdf.cell(0, 6, "Generated by clinical-image-ai | github.com/Sandyyy123/clinical-image-ai", ln=True)
        pdf.output(str(report_path))
        print(f"[INFO] PDF report saved: {report_path}")

    except ImportError:
        _txt_report(results, report_path, guideline)
